% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Wed Jun  1 15:49:18 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrr}
  \hline
Dataset & GH $7^5$ & SGI & Monomial \\ 
  \hline
1 & 7083.95 & 616.63 & 644.52 \\ 
  1 & 9142.16 & 549.22 & 578.42 \\ 
  1 & 4940.91 & 269.22 & 449.30 \\ 
  1 & 6184.56 & 414.71 & 294.48 \\ 
  1 & 5952.06 & 432.32 & 443.86 \\ 
   \hline
\end{tabular}
\caption{CPU time required by SNOPT for Dataset 1 by rule.}
\end{center}
\end{table}
