% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Wed Jun  1 15:49:18 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrr}
  \hline
Dataset & GH $7^5$ & pMC R=1,000 & pMC R=10,000 \\ 
  \hline
1 & 7083.95 & 366.80 & 8035.81 \\ 
  1 & 9142.16 & 753.15 & 5744.15 \\ 
  1 & 4940.91 & 632.36 & 3308.05 \\ 
  1 & 6184.56 & 687.31 & 3341.52 \\ 
  1 & 5952.06 & 740.08 & 7782.77 \\ 
   \hline
\end{tabular}
\caption{CPU time required by SNOPT for Dataset 1 by rule.}
\end{center}
\end{table}
