% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:17 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
$\theta_{11}$ & $\theta_{12}$ & $\theta_{13}$ & $\theta_{14}$ & $\theta_{15}$ \\ 
  \hline
2.6 & 1.4 & $-$1.7 & $-$13 & $-$10 \\ 
  1.1 & 1.6 & 1.6 & 0.097 & $-$2.6 \\ 
  1.1 & 1.6 & 1.6 & 0.097 & $-$2.6 \\ 
  $-$11 & $-$2.9 &  $-$4 &   1 & $-$5.4 \\ 
  $-$2.3 & 3.8 & 3.9 & $-$2.2 & $-$3.3 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: SGI with 993 nodes (exact for degree $\leq 11$)}
\label{TabPointEstSGI}
\end{center}
\end{table}
