% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:17 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
$\theta_{11}$ & $\theta_{12}$ & $\theta_{13}$ & $\theta_{14}$ & $\theta_{15}$ \\ 
  \hline
1.1 & 1.6 & 1.6 & 0.081 & $-$2.6 \\ 
  1.1 & 1.6 & 1.6 & 0.081 & $-$2.6 \\ 
  1.1 & 1.6 & 1.6 & 0.081 & $-$2.6 \\ 
  1.2 & 1.6 & 1.6 & 0.13 & $-$2.6 \\ 
  1.1 & 1.6 & 1.6 & 0.081 & $-$2.6 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: pMC with $R = 10,000$ draws}
\label{TabPointEstpMC-R10000}
\end{center}
\end{table}
