% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:18 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
$\theta_{11}$ & $\theta_{12}$ & $\theta_{13}$ & $\theta_{14}$ & $\theta_{15}$ \\ 
  \hline
1.1 & 1.6 & 1.6 & 0.1 & $-$2.6 \\ 
  2.1 & 0.22 & 0.25 & 1.7 & $-$2.8 \\ 
  1.1 & 1.6 & 1.6 & 0.1 & $-$2.6 \\ 
  1.1 & 1.6 & 1.6 & 0.1 & $-$2.6 \\ 
  1.1 & 1.6 & 1.6 & 0.1 & $-$2.6 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: Gauss-Hermite with $5^5$ nodes}
\label{TabPointEstGH5}
\end{center}
\end{table}
