% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:27:38 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{lllll}
  \hline
$\theta_{21}$ & $\theta_{22}$ & $\theta_{23}$ & $\theta_{24}$ & $\theta_{25}$ \\ 
  \hline
3.086e-06 &  1.055 & 2.230e-06 & 0.7183 & 0.3442 \\ 
  (2.280E+05) & (0.07972) & (3.417E+04) & (0.1011) & (0.04931) \\ 
   \hline
\end{tabular}
\caption{Point Estimates: Gauss-Hermite with first $5$ good starts and $7^5$ nodes}
\end{center}
\end{table}
