% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:18 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
$\theta_{21}$ & $\theta_{22}$ & $\theta_{23}$ & $\theta_{24}$ & $\theta_{25}$ \\ 
  \hline
  1 & 0.59 & 0.46 & 0.52 & 0.23 \\ 
  0.082 & 1.4 & 0.5 & 9.2 & 0.27 \\ 
    1 & 0.59 & 0.46 & 0.52 & 0.23 \\ 
    1 & 0.59 & 0.46 & 0.52 & 0.23 \\ 
    1 & 0.59 & 0.46 & 0.52 & 0.23 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: Gauss-Hermite with $5^5$ nodes}
\label{TabPointEstGH5}
\end{center}
\end{table}
