% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:17 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
$\theta_{21}$ & $\theta_{22}$ & $\theta_{23}$ & $\theta_{24}$ & $\theta_{25}$ \\ 
  \hline
 10 & 0.62 & 2.6 & 0.092 &  10 \\ 
    1 & 0.59 & 0.46 & 0.52 & 0.22 \\ 
    1 & 0.59 & 0.46 & 0.52 & 0.22 \\ 
  3.1 & 0.16 & 0.03 & 4.7 & 7.2 \\ 
  7.2 & 7.1 &   3 & 7.1 & 1.2 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: SGI with 993 nodes (exact for degree $\leq 11$)}
\label{TabPointEstSGI}
\end{center}
\end{table}
