% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:17 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
$\theta_{21}$ & $\theta_{22}$ & $\theta_{23}$ & $\theta_{24}$ & $\theta_{25}$ \\ 
  \hline
  1 & 0.57 & 0.54 & 0.52 & 0.23 \\ 
    1 & 0.57 & 0.54 & 0.52 & 0.23 \\ 
    1 & 0.57 & 0.54 & 0.52 & 0.23 \\ 
    1 & 0.61 & 0.51 & 0.5 & 0.24 \\ 
    1 & 0.57 & 0.54 & 0.52 & 0.23 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: pMC with $R = 10,000$ draws}
\label{TabPointEstpMC-R10000}
\end{center}
\end{table}
