% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:18 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 0 & 1 & 35.18956 & 1622.55 \\ 
  1 & 10 & 72 & 355.05860 & 90.76 \\ 
  1 & 0 & 1 & 35.18966 & 1630.59 \\ 
  1 & 0 & 1 & 35.18951 & 1837.82 \\ 
  1 & 0 & 1 & 35.18952 & 1052.61 \\ 
   \hline
\end{tabular}
\caption{MPEC Results: Gauss-Hermite with $5^5$ nodes}
\label{TabSolverResultsGH5}
\end{center}
\end{table}
