% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:16 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 0 & 1 & 33.50960 & 407.83 \\ 
  1 & 0 & 1 & 35.50762 & 795.43 \\ 
  1 & 0 & 1 & 35.08560 & 448.22 \\ 
  1 & 0 & 1 & 33.50963 & 450.86 \\ 
  1 & 0 & 1 & 37.31654 & 667.14 \\ 
   \hline
\end{tabular}
\caption{MPEC Results: pMC with $R = 1,000$ draws}
\label{TabSolverResultspMC}
\end{center}
\end{table}
