% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:19 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
5 & 0 & 1 & 293.89029 & 494.45 \\ 
  5 & 0 & 1 & 293.89029 & 571.11 \\ 
  5 & 0 & 1 & 293.89029 & 481.82 \\ 
  5 & 0 & 1 & 293.89029 & 556.80 \\ 
  5 & 0 & 1 & 487.40742 & 6535.28 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: SGI with first $5$ good starts and 993 nodes (exact for degree $\leq 11$)}
\label{TabSolverResultsSGI5Good}
\end{center}
\end{table}
