% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:16 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 0 & 1 & 34.75771 & 8035.81 \\ 
  1 & 0 & 1 & 34.75772 & 5744.15 \\ 
  1 & 0 & 1 & 34.75771 & 3308.05 \\ 
  1 & 0 & 1 & 33.71660 & 3341.52 \\ 
  1 & 0 & 1 & 34.75776 & 7782.77 \\ 
   \hline
\end{tabular}
\caption{MPEC Results: pMC with $R = 10,000$ draws}
\label{TabSolverResultspMC-R10000}
\end{center}
\end{table}
