% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:20 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
5 & 0 & 1 & 288.69920 & 6334.33 \\ 
  5 & 0 & 1 & 288.69920 & 7553.43 \\ 
  5 & 0 & 1 & 288.69920 & 7164.02 \\ 
  5 & 0 & 1 & 288.69920 & 8156.16 \\ 
  5 & 0 & 1 & 288.69920 & 5521.13 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: Gauss-Hermite with first $5$ good starts and $7^5$ nodes}
\label{TabSolverResultsGH7-5Good}
\end{center}
\end{table}
