% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:17 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 10 & 72 & 342.02594 & 54.88 \\ 
  1 & 0 & 1 & 35.27227 & 443.56 \\ 
  1 & 0 & 1 & 35.27220 & 658.89 \\ 
  1 & 10 & 72 & 7940.63473 & 25.24 \\ 
  1 & 10 & 72 & 288.31905 & 63.40 \\ 
   \hline
\end{tabular}
\caption{MPEC Results: SGI with 993 nodes (exact for degree $\leq 11$)}
\label{TabSolverResultsSGI}
\end{center}
\end{table}
