% latex table generated in R 2.11.1 by xtable 1.5-6 package
% Mon Oct 25 22:42:15 2010
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 0 & 1 & 35.27236 & 616.63 \\ 
  1 & 0 & 1 & 35.27217 & 549.22 \\ 
  1 & 0 & 1 & 35.27212 & 269.22 \\ 
  1 & 0 & 1 & 35.27216 & 414.71 \\ 
  1 & 0 & 1 & 35.27212 & 432.32 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: SGI with first $5$ good starts and 993 nodes (exact for degree $\leq 11$)}
\label{TabSolverResultsSGI5Good}
\end{center}
\end{table}
