% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:19 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
5 & 0 & 1 & 203.50784 & 668.71 \\ 
  5 & 0 & 1 & 213.97591 & 503.92 \\ 
  5 & 0 & 1 & 203.50784 & 626.74 \\ 
  5 & 0 & 1 & 208.76144 & 489.06 \\ 
  5 & 0 & 1 & 208.76144 & 696.81 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: pMC with First $5$ good starts and $R = 1,000$ draws}
\label{TabSolverResultspMC5Good-R01000}
\end{center}
\end{table}
