% latex table generated in R 2.11.1 by xtable 1.5-6 package
% Mon Oct 25 22:42:15 2010
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 0 & 1 & 33.23675 & 366.80 \\ 
  1 & 0 & 1 & 33.23675 & 753.15 \\ 
  1 & 0 & 1 & 33.85679 & 632.36 \\ 
  1 & 0 & 1 & 33.23681 & 687.31 \\ 
  1 & 0 & 1 & 38.53239 & 740.08 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: pMC with First $5$ good starts and $R = 1,000$ draws}
\label{TabSolverResultspMC5Good-R01000}
\end{center}
\end{table}
