% latex table generated in R 2.11.1 by xtable 1.5-6 package
% Mon Oct 25 22:42:15 2010
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 0 & 1 & 34.63546 & 644.52 \\ 
  1 & 0 & 1 & 34.63550 & 578.42 \\ 
  1 & 0 & 1 & 34.63556 & 449.30 \\ 
  1 & 0 & 1 & 34.63552 & 294.48 \\ 
  1 & 0 & 1 & 34.63548 & 443.86 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: Monomial with First $5$ Good Starts.}
\label{TabSolverResultsMono5Good}
\end{center}
\end{table}
