% latex table generated in R 2.11.1 by xtable 1.5-6 package
% Mon Oct 25 22:42:16 2010
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
1 & 0 & 1 & 35.05646 & 7083.95 \\ 
  1 & 0 & 1 & 35.05639 & 9142.16 \\ 
  1 & 0 & 1 & 35.05644 & 4940.91 \\ 
  1 & 0 & 1 & 35.05639 & 6184.56 \\ 
  1 & 0 & 1 & 35.05651 & 5952.06 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: Gauss-Hermite with first $5$ good starts and $7^5$ nodes}
\label{TabSolverResultsGH7-5Good}
\end{center}
\end{table}
