% latex table generated in R 2.12.2 by xtable 1.5-6 package
% Fri May 20 00:23:18 2011
\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrr}
  \hline
Dataset & EXIT & INFORM & f\_k & CPU Time \\ 
  \hline
5 & 0 & 1 & 277.89463 & 441.45 \\ 
  5 & 0 & 1 & 278.03790 & 441.77 \\ 
  5 & 0 & 1 & 277.89463 & 548.75 \\ 
  5 & 0 & 1 & 277.89463 & 1134.53 \\ 
  5 & 0 & 1 & 278.03790 & 656.13 \\ 
   \hline
\end{tabular}
\caption{Point Estimates: Monomial with First $5$ Good Starts.}
\label{TabSolverResultsMono5Good}
\end{center}
\end{table}
